version: '3.7'

networks:
  elastic:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.1
    restart: on-failure:5
    container_name: elasticsearch
    environment:
      cluster.name: "docker-cluster"
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      http.host: "elasticsearch"
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
      network.host: 0.0.0.0
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.1
    restart: on-failure:5
    container_name: kibana
    environment:
      SERVER_NAME: "kibana"
      ELASTICSEARCH_URL: "http://elasticsearch:9200/"
      XPACK_GRAPH_ENABLED: "true"
      XPACK_ML_ENABLED: "true"
      XPACK_MONITORING_ENABLED: "true"
      XPACK_REPORTING_ENABLED: "true"
      XPACK_SECURITY_ENABLED: "true"
      XPACK_WATCHER_ENABLED: "true"
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: "true"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    volumes:
      - ./kibana/config:/usr/share/kibana/config
    networks:
      - elastic
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.1
    restart: on-failure:5
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./monitored_folder/:/usr/share/logs
    networks:
      - elastic
    ports:
      - 5000:5000
      - 9600:9600
    depends_on:
      - elasticsearch
